### ISSUE TITLE
[PE-D][Tester D] Dark theme doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#102]
Dark theme command has no response.

![Screenshot 2024-04-05 at 4.16.08 PM.png](https://raw.githubusercontent.com/officialchengyud/ped/main/files/2b6ef731-d061-4f09-a288-0f9ab4c8ec3e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: officialchengyud/ped#3

**Comment by wilsonwid** [comment]
Duplicate issue.
