### ISSUE TITLE
[PE-D][Tester C] Field allows non English language but cannot display in correct format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#105]
![2.png](https://raw.githubusercontent.com/nuyer/ped/main/files/a62deaba-6d49-43e6-91c1-29fd06bc73f3.png)

Steps
1 edit contact to contain address with thai language edit 2 e/ร่กดนรสือ่สา
2 list the contact

Expect: either
1 error message cannot accpet non english language
2 correct display in different language

Actual:
Accept non english character but cannot display

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nuyer/ped#2

**Comment by sarjinius** [comment]
This bug does not show on my end, the text is properly shown in the message and list.

**Comment by wilsonwid** [comment]
Documentation fixed.
