### ISSUE TITLE
[PE-D][Tester D] Tip for exporting subset of data wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#113]
It should be: 

`Tip: FILENAME is optional. If [provided], has to be a valid filename with a .json or .csv extension.`

![Screenshot 2024-04-05 at 4.25.12 PM.png](https://raw.githubusercontent.com/officialchengyud/ped/main/files/f9066600-418d-4709-97a7-b7ff4daf8204.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: officialchengyud/ped#6

**Comment by wilsonwid** [comment]
Fixed.
