### ISSUE TITLE
[PE-D][Tester C] Calendar_view cannot display the whole duration for a schedule

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#114]
My schedule is "Meeting" from 2024-04-04 to 2024-04-21
but calendar view only shows meeting on 4 april.
This may cause confusion

![5.png](https://raw.githubusercontent.com/nuyer/ped/main/files/e842b781-0008-4ff8-89d1-584a390a4cc0.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nuyer/ped#5

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4
