### ISSUE TITLE
[PE-D][Tester B] Constraints in the user guide and constraints in the error message for add command is different.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#115]
**Maybe it would be good to could indicate in the user guide that the user cannot add special names that are not alphanumeric?**

<hr>

**Constraints in user guide do not indicate that name should be alphanumeric**
![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/df21e450-4972-4922-82e0-1f40d27db9af.png)

<hr>

**Constraints in error message indicates that name should be alphanumeric**
![Screenshot 2024-04-05 at 4.27.05 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/0515086a-a244-4c4e-bab4-ae82619a649d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#4

**Comment by wilsonwid** [comment]
Fixed.
