### ISSUE TITLE
[PE-D][Tester D] Documentation for Delete needs changes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#116]
Documentation mentions you can use `find Betsty` followed by `delete 1`.
However, this is incongruous with your documentation for the `find` command. It should be `find n/Betsty`.

![Screenshot 2024-04-05 at 4.29.29 PM.png](https://raw.githubusercontent.com/officialchengyud/ped/main/files/7a13529e-abea-46b8-9cc9-60a55b35948f.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: officialchengyud/ped#7

**Comment by wilsonwid** [comment]
Fixed.
