### ISSUE TITLE
[PE-D][Tester D] Add schedule start time can be before end time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#121]
The `add_schedule` command allows me to set a start time that is before the end time (which doesn't make logical sense).

![Screenshot 2024-04-05 at 4.34.29 PM.png](https://raw.githubusercontent.com/officialchengyud/ped/main/files/575273b3-d97b-4ebd-8818-e7eb0e9c411b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: officialchengyud/ped#9

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4.
