### ISSUE TITLE
[PE-D][Tester B] Add command is very strict because the user has to type out all 4 fields to insert a contact

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#126]
Maybe instead of requiring users to enter all `name, phone, email, address` we could make it less restrictive and require just `name, phone` first? So if the user is in a rush they can quickly add a contact first?

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/a0d2ff5d-a25d-47fa-b0b4-bcae313f9754.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: bgopi23/ped#7

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4.
