### ISSUE TITLE
[PE-D][Tester B] Inconsistent error messages for edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#129]
**Since we have an invalid index maybe the error message could indicate that the index is invalid instead of telling the user to add a field to edit?
Because lets say that the user enters `edit 200000`, even though this is an invalid index, it prompts the user to enter more fields as shown below** 

<hr>

![Screenshot 2024-04-05 at 4.45.03 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/c3a1cc7c-b405-4e89-8b7f-375fb0b1b722.png)

**However, upon adding a field to edit, then it indicates that the index is invalid. Maybe it would be good to first make sure the index is valid before prompting the user to enter more fields?**

![Screenshot 2024-04-05 at 4.45.37 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/fc0121f5-d0a2-409f-86c7-515e9532a7a8.png)

*Still I really appreciate that you caught both edge cases of invalid indexes and empty parameters :)*

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#8

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4.
