### ISSUE TITLE
[PE-D][Tester A] Instructions wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#133]
![image.png](https://raw.githubusercontent.com/YuZizhen/ped/main/files/d35fc2a2-057b-4336-bef0-9b5426d01dec.png)
The displayed instruction seems to be not of the right form.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: YuZizhen/ped#7

**Comment by ChuaZiLong** [comment]
This is done
