### ISSUE TITLE
[PE-D][Tester B] Inconsistent error messages for invalid indexes for delete command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#134]
**Since the indexes `-1` and `1000` are both invalid would it be better to instead use the same `Invalid Index` error message for both of these cases?**

<hr>

![Screenshot 2024-04-05 at 4.51.55 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/fbe09e21-4bb0-4acb-abd6-8086b9f2aee3.png)

![Screenshot 2024-04-05 at 4.52.07 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/f8eb4089-2e50-4891-8233-886f7bffade3.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#10

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4.
