### ISSUE TITLE
[PE-D][Tester A] Phone number too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#137]
![image.png](https://raw.githubusercontent.com/YuZizhen/ped/main/files/d6b8c76c-3855-4494-921f-e45ab07f0eac.png)
It is better to restrict the length of the phone number to be less than 15 digits.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: YuZizhen/ped#8

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4.
