### ISSUE TITLE
[PE-D][Tester B] Calendar glitches when resizing for calendar_view command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#146]
When resizing the window, the calendar glitches.

**Maybe it would be good to set a minimum window size in javafx to prevent the user from resizing it too small by accident?**

<hr>

**How it looks originally**
![Screenshot 2024-04-05 at 10.45.27 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/8fdd743f-27bd-4dc4-94dd-84ec94da7a3f.png)

<hr>

**How it looks after resizing**
![Screenshot 2024-04-05 at 10.42.52 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/e6ee89f8-4475-4320-afd3-dc4acb76382c.png)

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/a84818bf-3edf-47c1-a92f-62c4b4459798.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#14

**Comment by wilsonwid** [comment]
Not allowed to fix in v1.4, and not a bug.
