### ISSUE TITLE
[PE-D][Tester B] Application gets stuck when inputting invalid year for add schedule command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#147]
When adding schedules with an invalid start year, the application gets stuck and does not produce any error message and does not add the schedule either.

**Maybe it would be good to add a check to parse and produce an error for invalid years to prevent the application from getting stuck?**

**I have included the command which caused this behaviour for your reference below**

<hr>

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/ce8ff64c-a059-4f80-9adb-752444504cc5.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#15

**Comment by sarjinius** [comment]
Resolved
