### ISSUE TITLE
[PE-D][Tester B] empty end/ for add_command causes the application to get stuck

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#150]
**Maybe it would be good to produce an error message to indicate that the end/ attribute cannot be empty?**
<hr>

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/f4af4fce-0dd1-4d42-a80a-def370de3ced.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#18

**Comment by sarjinius** [comment]
Resolved
