### ISSUE TITLE
[PE-D][Tester B] Overflow when adding long tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#153]
**maybe we could wrap the text or make it scrollable to prevent long tag data from being blocked?**

<hr>

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/01bb1761-1c07-4b1d-be4f-f3367503ed37.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#21

**Comment by wilsonwid** [comment]
Not a bug.
