### ISSUE TITLE
[PE-D][Tester A] Identification of different persons

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#157]
![image.png](https://raw.githubusercontent.com/YuZizhen/ped/main/files/153d93fe-a651-4b50-89ff-da5ead7c8f22.png)
It might be better to consider two persons with same name and telephone number be the same person.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: YuZizhen/ped#9

**Comment by wilsonwid** [comment]
Not a bug.
