### ISSUE TITLE
[PE-D][Tester A] Clicking of the buttom

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#160]
![image.png](https://raw.githubusercontent.com/YuZizhen/ped/main/files/696e5e77-a0ce-4a97-b58b-9725479c1779.png)
These two buttoms can be clicked but only pops up a "Exit" and "Help F1" respectively.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: YuZizhen/ped#12

**Comment by wilsonwid** [comment]
Not a bug.
