### ISSUE TITLE
As a user, I want to import/export my contact list in a common format

### ISSUE THREAD

**Issue by wilsonwid** [AY2324S2-CS2103T-W08-3/tp#51]
... so that I can back up my data and import/export it from/to other applications.

**Comment by tahsinhasem** [comment]
If anyone else is not doing it, I can prolly start doing this, exporting contacts to a .csv file following the Google Contacts CSV format

**Comment by wilsonwid** [comment]
> If anyone else is not doing it, I can prolly start doing this, exporting contacts to a .csv file following the Google Contacts CSV format

@tahsinhasem Please complete v1.1 before writing this feature. Thanks!

**Comment by tahsinhasem** [comment]
@wilsonwid noted boss

**Comment by wilsonwid** [comment]
Moved to v1.3 as this is a less-important issue to have in the MVP.
